### ISSUE TITLE
ctpn_train batch=1 change to 128 get error

### ISSUE THREAD

**Issue by zhuchangjiang** [opconty/pytorch_ctpn#3]
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    checkpoints_weight = args['pretrained_weights']
    if os.path.exists(checkpoints_weight):
        pretrained = False

    dataset = VOCDataset(args['image_dir'], args['labels_dir'])
    dataloader = DataLoader(dataset, batch_size=**128**, shuffle=True, num_workers=args['num_workers'])
    model = CTPN_Model()
    model.to(device)

Traceback (most recent call last):
  File "ctpn_train.py", line 91, in <module>
    for batch_i, (imgs, clss, regrs) in enumerate(dataloader):
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/zhanglijun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 562 and 600 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1333

**Comment by fxwispig** [comment]
这个只能使用batch_size为1

**Comment by opconty** [comment]
sorry for late reply
just as @fxwispig said, thanks

**Comment by unanan** [comment]
想问一下  bs=1能训的动吗？
